internal/push/logic/push_to_client.go
fix offline push bug,
1.check the wsResult 
if  is successful then continue 
else go to 2
2.check the supported terminal
if  is matched then Use offline push messaging
else continue
=> fix offline push bug

.gitignore, README.md, app.yaml, cmd/rpc/open_im_auth/main.go, config/config.dev.yaml, dev.Dockerfile, docker-compose.dev.yaml, docker-compose.local.yaml, internal/api/auth/user_register_test.go, pkg/common/config/config.go
=> feat: improve develop experience

pkg/common/db/mongoModel.go
将原来在群成员放在mysql的方法 改为用mongo管理，所以具体数据库方法已实现，上层对应接口未替换 ，本pr通过后 将进行替换
=> Group members changed from mysql to mongo for management

pkg/base_info/friend_api_struct.go
Signed-off-by: arthur <yang_yapo@126.com>
=> fix: json tag value of UserIDResult.UserID

cmd/open_im_api/main.go, config/config.yaml, deploy/config.example.yaml, go.mod, go.sum, internal/api/third/ali_oss_credential.go, pkg/base_info/oss_api_struct.go, pkg/common/config/config.go, pkg/common/db/model.go
=> 新增mongo.dbUrl配置

script/win_build_all_service.cmd, script/win_start_all_service.cmd
新增windows编译脚本，麻烦同步下
win_build_all_service.cmd windows下编译脚本
win_start_all_service.cmd windows下执行脚本
=> 新增windows编译脚本

config/config.yaml, internal/rpc/msg/rpcChat.go, pkg/common/config/config.go
您好，发现kafka中有废弃的暂时没有被使用的topic，因此我删除了部分冗余代码，并对kafka的topic的作用进行了解释
=> kafka topic优化及解释，删除废弃topic的冗余代码

config/config.yaml
=> 修复aws s3 配置

CONTRIBUTING.md
=> docs: design contributor documentation

.github/workflows/.mlc_config.json, .github/workflows/markdown.yml, README.md
This PR is just a test of the actions~
=> test: test cicd actions deplpy

script/githooks/commit-msg, script/githooks/pre-commit
</br>
🫰 Thanks for sending a pull request!  Here are some tips for you:
1. If this is your first time, please read our contributor guidelines: 
📇 https://github.com/OpenIMSDK/community/blob/main/CONTRIBUTING.md
2. Ensure you have added or ran the appropriate tests for your PR:
/kind feature
that is right Feature: Linux mandatory usage specifications #396 Close the book
Fixes #396
I think we still need a git hook to control the spec and this is my last summary of git hooks. And I wrote the content in GitHub gist
[https://gist.github.com/cubxxw/126b72104ac0b0ca484c9db09c3e5694](https://gist.github.com/cubxxw/126b72104ac0b0ca484c9db09c3e5694)
Pull to the local test
no
=> feat: supports and optimizes git hooks

.github/.codecov.yml, .github/workflows/link-pr.yml, CHANGELOG/.chglog/CHANGELOG.tpl.md, CHANGELOG/.chglog/config.yml, CHANGELOG/CHANGELOG-0.0.0.md, README_zh.md, script/make-rules/common.mk
Signed-off-by: Xinwei Xiong(cubxxw) <3293172751nss@gmail.com></br>
/kind feature
Fixes #406
=> ci: join the desgin of chglog and init

.github/workflows/auto-invite.yml, .github/workflows/issue-robot.yml
</br>
/kind feature
Fixes #409
=> feat: Translation and Commenting Bots

.github/workflows/auto-invite.yml
Signed-off-by: Xinwei Xiong(cubxxw) <3293172751nss@gmail.com></br>
Fixes #
=> feat: exchange tokens for the robot

.github/workflows/sync.yml
=> test: test robot form kubbot

config/config.yaml, go.mod, go.sum, internal/rpc/third/third.go, pkg/common/db/obj/obj.go, pkg/common/db/obj/tx_oss.go
=> add tx_oss cos

docker-compose.yaml
=> Docker compose bug

docker-compose.yaml
</br>
/kind feature
Fixes #486
=> feat: add the changelog

Dockerfile
=> fix: docker file path

pkg/common/db/relation/mysql_init.go
=> Add database retry

pkg/common/db/unrelation/extend_msg.go
=> chore: use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...))

pkg/common/db/s3/minio/minio.go
=> fix: minio auto make bucket

cmd/openim-api/main.go, config/config.yaml, pkg/common/cmd/rpc.go
=> fix conflict

.github/workflows/scripts-test.yml, docker-compose.yaml, scripts/msg_transfer_start.sh, scripts/start_all.sh
=> fix: scripts and release

Dockerfile, scripts/make-rules/image.mk
=> feat: Add light mode and dark mode.(#89)

build.cmd, internal/rpc/msg/server.go, pkg/common/db/controller/msg.go
</br>
Fixes #554
look Ci actions
=> message for your changes

internal/api/user.go, internal/msggateway/hub_server.go, pkg/common/db/cache/conversation.go
=> fix: implement of GetUsersOnlineStatus (#567)

config/config.yaml, pkg/common/db/controller/s3.go, pkg/common/db/s3/cos/cos.go, pkg/common/db/s3/minio/minio.go, pkg/common/db/s3/oss/oss.go, pkg/common/db/s3/s3.go
=> fix: s3 browser preview #579

internal/rpc/user/user.go, pkg/common/db/table/relation/user.go
=> fix: user app_manger_level#581

pkg/common/db/s3/minio/minio.go, pkg/common/db/s3/oss/oss.go
=> fix: Compatible with wasm s3 oss header Date

CONTRIBUTING.md
=> docs: fix lint update CONTRIBUTING.md

.github/workflows/golangci-lint.yml
=> Update and rename golangci-link.yml to golangci-lint.yml

pkg/proto/wrapperspb/wrapperspb.go
…rialization and deserialization fail
Fixes #643
=> fix: StringValue json serialization problem

.github/workflows/auto-release.yml, .github/workflows/link-pr.yml
=> feat: add file:

docs/CODEOWNERS
=> docs: update CODEOWNERS

README.md
=> docs: update README.md install

.goreleaser.yaml, Makefile, config/config.yaml, install.sh, scripts/advertise.sh, scripts/make-rules/copyright.mk, scripts/make-rules/golang.mk, scripts/style_info.sh
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com>
/kind feature
add openim install script 
https://gist.github.com/cubxxw/28f997f2c9aff408630b072f010c1d64
Fixes #674
=> feat: add openim log

go.mod, go.sum
=> fix: sql injection risk

go.mod, go.sum, internal/api/route.go, internal/api/user.go, internal/rpc/user/user.go, internal/tools/msg.go, pkg/common/db/controller/user.go, pkg/common/db/table/unrelation/user.go, pkg/common/db/unrelation/user.go
=> Resolving code conflicts after project directory changes and Add user subscription to the operation from rpc to db layer

.github/workflows/build-docker-image.yml, .github/workflows/deploy.yml, .goreleaser.yaml, Dockerfile, config/config.yaml, docs/conversions/images.md, docs/conversions/version.md, internal/rpc/group/group.go
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
Fixes #
=> docs: add readme docs

Dockerfile
/kind feature
https://github.com/OpenIMSDK/Open-IM-Server/issues/577
```
panic: ==> github.com/OpenIMSDK/Open-IM-Server/pkg/startrpc.Start()@93: : Get "https://storage.vibaike.com/openim/?location=": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
Fixes #577
=> fix: docker file fix

.github/workflows/build-docker-image.yml
=> fix bug: join group failed

CODE_OF_CONDUCT.md
=> docs: update create CODE_OF_CONDUCT.md

docs/conversions/images.md
docs: more about docker image install
=> docs: more about docker image install

docs/conversions/README.md
docs: update the document directory
=> docs: update the document directory   

internal/api/group.go, internal/api/route.go
=> feat: add get_group_member_user_id api

config/open-im-ng-example.conf
=> nginx minio configuration picture can not be sent

.github/workflows/scripts-test.yml, Dockerfile, build/docker/openim-api/Dockerfile, build/docker/openim-cmdutils/Dockerfile, build/docker/openim-crontask/Dockerfile, build/docker/openim-rpc-auth/Dockerfile, build/docker/openim-rpc-conversation/Dockerfile, build/docker/openim-rpc-friend/Dockerfile, build/docker/openim-rpc-group/Dockerfile, build/docker/openim-rpc-msg/Dockerfile, build/docker/openim-rpc-third/Dockerfile, build/docker/openim-rpc-user/Dockerfile, docker-compose.yaml, pkg/common/db/controller/user.go, scripts/msg_gateway_start.sh, scripts/msg_transfer_start.sh, scripts/push_start.sh, scripts/start_all.sh, scripts/start_cron.sh, scripts/stop_all.sh
<br>
/kind feature
Resolves #783, resolves #788,  resolves #784,  resolves #785
Link: #782
=> feat: fix scripts and build speed

internal/rpc/group/group.go
=> fix: create group type limit

internal/rpc/msg/sync_msg.go, pkg/common/db/controller/msg.go, pkg/common/db/unrelation/msg.go, scripts/start.bat
=> modify search msg

internal/rpc/group/group.go, pkg/common/db/controller/group.go, pkg/rpcclient/notification/group.go
=> fix: MemberEnterNotification 

Dockerfile, docker-compose.yaml, go.work, scripts/docker_start_all.sh, scripts/path_info.sh, scripts/start_all.sh, scripts/start_component_check.sh, tools/component/go.mod, tools/component/main.go
=> check components script

scripts/make-rules/golang.mk
<br>
Fixed typo.
```
Formating -> Formatting
```
Fixes #
=> fix: typo in golang.mk

go.mod, go.sum, go.work.sum, internal/api/route.go, internal/rpc/user/user.go, pkg/common/db/cache/user.go, pkg/rpcclient/user.go
=> Fix bug #862

docker-compose.yaml, openim-chat/config/config.yaml, openim-chat/scripts/LICENSE/LICENSE, openim-chat/scripts/LICENSE/LICENSE_TEMPLATES, openim-chat/scripts/admin_rpc_start.sh, openim-chat/scripts/build.cmd, openim-chat/scripts/build_all_service.sh, openim-chat/scripts/build_docker.sh, openim-chat/scripts/check_all.sh, openim-chat/scripts/docker_start_all.sh, openim-chat/scripts/function.sh, openim-chat/scripts/githooks/commit-msg, openim-chat/scripts/githooks/pre-commit, openim-chat/scripts/githooks/pre-push, openim-chat/scripts/path_info.sh, openim-chat/scripts/start.bat, openim-chat/scripts/start_all.sh, openim-chat/scripts/stop_all.sh, openim-chat/scripts/style_info.sh, scripts/docker_check_service.sh, tools/component/main.go
=> chore: to map files of chat docker image into the IM server

.github/sync.yml
=> docs: update sync file

go.mod, go.sum, go.work.sum, internal/rpc/msg/revoke.go
=> fix: admin revoke msg

.env, config/config.yaml, deployments/templates/openim.yaml, scripts/README.md, scripts/demo.sh, scripts/lib/color.sh
<br>
/kind feature
Fixes #917
read: #917
```bash
$ make demo
```
=> fix: images bug find tput in make demo

test/data-conversion/kafka-conversation.go, test/data-conversion/kafka_test.go, test/data-conversion/mongodb-conversion.go, test/data-conversion/mysql-conversion.go, test/data-conversion/mysql_test.go, test/data-conversion/redis-conversion.go
=> MySQL Data conversion

internal/api/msg.go, pkg/apistruct/msg.go
=> fix: send text message by api doesn't work.

internal/api/msg.go
=> fix: send text message by api doesn't work. #929

.github/sync.yml
<br>
/kind feature
feat: Automating openim-docker synchronization
Fixes #961
CICD 
https://github.com/OpenIMSDK/openim-docker
=> feat: Automating openim-docker synchronization

.github/sync-release.yml
🔍 What type of PR is this?
/kind feature
👀 What this PR does / why we need it:
My pull request adheres to the code style of this project
My code requires changes to the documentation
I have updated the documentation as required
All the tests have passed
feat: Automating openim-docker synchronization
🅰 Which issue(s) this PR fixes:
Fixes #961
📝 Special notes for your reviewer:
🎯 Describe how to verify it
CICD
[OpenIMSDK/openim-docker](https://github.com/OpenIMSDK/openim-docker)
📑 Additional documentation e.g., RFC, notion, Google docs, usage docs, etc.:
=> feat: create sync-release.yml

internal/api/msg.go, pkg/apistruct/msg.go
=> refactor:Optimization of text messages when accepting message req

internal/rpc/conversation/conversaion.go
=> chore: optimize modification and send notifications

internal/rpc/conversation/conversaion.go
=> fix: repeated modification session notification

internal/push/push_to_client.go, internal/rpc/conversation/conversaion.go
=> fix: jpush return a nil pointer panic

go.work
=> fix: go work update go.work

README.md
=> docs: update openim readme

scripts/demo.sh
=> feat: update demo scripts

docker-compose.yaml
=> fix(release-v3.2)-docker compose fix port and host

docker-compose.yaml
=> fix: v3.2 update docker-compose.yaml

docker-compose.yaml
=> fix: openim-server Mirrored the pull

docker-compose.yml
=> fix: openim logs release v3.3

scripts/install/environment.sh
=> fix update environment.sh

go.work, internal/rpc/group/group.go, internal/rpc/user/user.go, pkg/common/convert/group.go
=> fix: modifying user information notifications to join groups and group avatar issues

README.md
=> docs(main): update openim readme

.golangci.yml, cmd/openim-api/main.go, internal/api/third.go, internal/msggateway/long_conn.go, internal/rpc/third/log.go, pkg/common/db/cache/conversation.go, pkg/common/db/controller/third.go, pkg/common/db/relation/log_model.go, tools/component/component.go
<br>
Fixes #781
```
make lint
```
=> fix: make lint about cicd

docs/contrib/environment.md, docs/contrib/install_docker.md
=> docs: add openim docs

internal/api/msg.go
=> fix: api send msg update.

README-zh_CN.md
#1193
Add English translation for README.md
- Introduced README_EN.md containing English translations of the original README file.
- Included a link to README_EN.md in the original README.md for accessibility.
<br>
/kind feature
Fixes #1193
**Description**:
This PR introduces an English translation of the `README.md` file to ensure the OpenIMSDK is accessible and understandable to a global audience.
**Changes Introduced**:
+ Added `README_EN.md`, an English translation of the original README file.
+ Updated original `README.md` to include a link to the English version for easy navigation and accessibility.
**How to Test**:
+ Review `README_EN.md` for any translation errors or inconsistencies with the original text.
+ Ensure that all links, formatting, and content …
=> Docs(main): Add English translation for README.md

pkg/common/db/relation/log_model.go
/kind feature
#1249 
Fixes #1249
=> feat:order logs by time desc

internal/msggateway/init.go, pkg/common/cmd/root.go, pkg/common/startrpc/doc.go, pkg/common/startrpc/start.go
=> fix: golint code format and error log trace

go.mod, internal/rpc/msg/sync_msg.go, pkg/common/discovery_register/k8s_discovery_register.go, pkg/common/startrpc/start.go
=> fix: zk add close to avoid zk block.

Makefile, README.md
=> docs: update readme docs

pkg/common/http/http_client.go
Modified the number of http client connections. The default number of connections to the same host is 2. When the concurrency exceeds 2, short connections will appear, and a large number of timewait can be seen in the system. 
In addition, short connections affect access performance because the request When the request is made, a connection is required, and the connection is closed after the request.
1. reset MaxConnsPerHost value.
2. format code.
3. set default max timeout on client.
=> perf: http client transport

internal/rpc/group/group.go
=> fix: error when querying some information about disbanded group

.github/workflows/build-docker-image.yml
=> build: build openim image

internal/push/push_to_client.go, pkg/common/config/config.go
1. add `maxConcurrentWorkers ` in config.
2. broadcast msg to all gateway with concurrency.
3. pervent to alloc OnlineBatchPushOneMsgReq multiple times.
=> perf: broadcast msg to all gateway with concurrency

pkg/common/db/cache/msg.go, pkg/common/db/cache/msg_test.go
- rm unused object
- batch delete msgs
- pipeline delete msgs
=> perf: redis batch delete msgs

deployments/templates/env_template.yaml, docs/contrib/environment.md, docs/contrib/prometheus-grafana.md, scripts/install/environment.sh, scripts/install/install-protobuf.sh
=> feat: deployment and design of management backend and monitoring

cmd/openim-api/main.go
add graceful shutdown operation for open-im api server.
=> fix: grace shutdown for api server

config/instance-down-rules.yml, internal/msgtransfer/init.go, internal/msgtransfer/online_history_msg_handler.go, internal/rpc/msg/sync_msg.go, pkg/common/db/cache/msg.go, pkg/common/db/controller/msg.go
=> Feature middleware

deployments/README.md, deployments/templates/chat.yaml, deployments/templates/env_template.yaml, deployments/templates/openim.yaml, docs/contrib/environment.md, scripts/install-im-server.sh, scripts/install/common.sh, scripts/install/dependency.sh, scripts/install/environment.sh
Signed-off-by: Xinwei Xiong(cubxxw) <3293172751nss@gmail.com>
<br>
/kind feature
**about `fix make init`
/kind bug
Could you please help me write a PR description? The task is to modify the code logic by changing the password reading strategy from the configuration file to reading from environment variables. The PR should have the following title: "feat: Provides a new reading scheme for profile privacy through environment variables". Thank you so much for your assistance!
Fixes #1516
Resolves #1496,
**Mysql -> Mongo**
Fixes #1505
=> fix: remove docker compose mysql

internal/rpc/group/group.go
<br>
- [x ] My pull request adheres to the code style of this project
- [x ] My code requires changes to the documentation
- [x ] I have updated the documentation as required
- [x ] All the tests have passed
#1555 
Fixes #
=> fix group notification

README.md
=> docs: Update README.md and add openim web online demo address

pkg/common/db/cache/init_redis.go, pkg/common/discoveryregister/discoveryregister_test.go, pkg/common/discoveryregister/zookeeper/zookeeper.go, pkg/common/kafka/producer.go, pkg/common/kafka/util.go, tools/component/component_test.go
<br>
/kind feature
Fixes #1624
=> fix: fix openim zk env set

pkg/common/db/unrelation/mongo.go
=> fix: mongo uri connect

docker-compose.yml, pkg/common/discoveryregister/kubernetes/kubernetes.go
Signed-off-by: Xinwei Xiong (cubxxw) <3293172751nss@gmail.com>
<br>
Could you please assist in resolving the issue with mirroring the repository's versions?
Fixes #1647
=> fix openim-admin images name 

go.mod, go.sum, internal/rpc/user/user.go, scripts/install-im-server.sh
=> fix: update Notification update resp 

go.mod, internal/rpc/user/user.go, pkg/authverify/token.go, pkg/common/db/controller/user.go, pkg/common/db/mgo/user.go, pkg/common/db/table/relation/user.go, pkg/rpcclient/user.go
=> fix: fix the imAdmin permission and searchNoficitaion resp

deployments/templates/env-template.yaml, deployments/templates/openim.yaml, docker-compose.yml, pkg/common/db/unrelation/mongo.go, scripts/install/environment.sh, scripts/mongo-init.sh, tools/component/component.go
=> MongoDB supports non-root users

docs/contrib/environment.md, pkg/common/db/unrelation/mongo.go, scripts/install/dependency.sh
fix openim config mongo passwd env
=> fix openim config mongo passwd env

.github/workflows/openimci.yml, docs/contrib/environment.md, pkg/common/db/unrelation/mongo.go, scripts/install-im-server.sh, scripts/install/dependency.sh
Signed-off-by: Xinwei Xiong (cubxxw) <3293172751nss@gmail.com>
Fixed: #1691
=> Fix(main): fix openim config from mongo password env upgrade openim build CICD

.github/workflows/cla.yml
I hope this message finds you well. I am reaching out to request your assistance in crafting a compelling title and description for a recent PR update.
The update involves enhancing the GitHub actions for CLA, enabling the robot to bypass CLA verification.
Your expertise in this matter would be greatly appreciated, and I am confident that your input will contribute to the success of this PR.
Thank you for considering my request, and I look forward to your valuable input.
=> Request for Assistance with PR Title and Description Update cla.yml

internal/api/msg.go
=> feat: send msg at text

go.mod, go.sum, internal/rpc/user/user.go, pkg/common/db/controller/user.go, pkg/common/db/mgo/user.go, pkg/common/db/table/relation/user.go
=> fix: fix some bug

pkg/common/db/controller/conversation.go
=> fix: group messages sync failed.

go.mod, internal/api/conversation.go, internal/api/route.go, internal/rpc/conversation/conversaion.go, internal/rpc/user/user.go
=> fix: fix the getSortedConversationList api

go.mod, go.sum, internal/api/conversation.go, internal/api/route.go, internal/rpc/conversation/conversaion.go, internal/rpc/user/user.go
=> fix: fix the GetSortedConversationList

pkg/common/db/mgo/user.go
=> fix: fix the mongo search error

internal/rpc/group/group.go, pkg/rpcclient/notification/group.go
=> fix: GroupApplicationRejectedNotification not notification apply for userID

scripts/install/openim-tools.sh
<br>
/kind feature
I have successfully resolved the issue with the mirror for the release branch and also fixed the problem with the tools not being able to output to log files.
=> docs: update oepnim docs openim-tools images

scripts/lib/util.sh
PR has fixed some finer details in Mac deployment. Thank you!
=> fix: mac deployment

docker-compose.yml
Description:
This pull request (PR) addresses the need for stability by pinning specific Docker image versions in the docker-compose configuration for minio and openim-web services. By specifying the exact image versions, we ensure that the system operates consistently and minimizes any potential issues arising from image updates. This enhancement will contribute to a more reliable and predictable deployment environment for these services.
Key Changes:
- Docker Compose configuration files have been updated to include specific image version tags for minio and openim-web.
- The pinned image versions have been tested to ensure compatibility and stability within the compose environment.
- Documentation has been updated to reflect the new image version requirements.
=> Stability Enhancement: Pin Docker Compose Images for minio and openim-web

internal/api/msg.go
(cherry picked from commit ceb950a57f766f1887295c3d07eb6967d3341d51)
<br>
Fixes #1703
=> feat: send msg at text (#1705)

docker-compose.yml
**Proposed Changes:**
Add support for the `linux/amd64` platform to enable multi-architecture deployment for openim-web and openim-admin.
Currently, the project's Docker images may only work on specific platform architectures, limiting deployment flexibility. This PR aims to enhance the project's deployability by ensuring compatibility with the `linux/amd64` platform, allowing seamless deployment across various architectures.
- Added support for building Docker images for the `linux/amd64` platform.
- Ensured that the image processes are not dependent on the underlying system to enable cross-architecture execution.
- This PR represents a part of multi-architecture deployment for the project and may require further testing and optimization.
- Please ensure thorough testing on the …
=> Update docker-compose.yaml support arm/v6, arm/v8

deployments/templates/openim.yaml, internal/rpc/msg/as_read.go, pkg/callbackstruct/message.go
=> fix: change the afterSendSingleMsg config and fix CallbackSingleMsgRead unused problem

scripts/install/openim-tools.sh
This Pull Request introduces an improvement in our component monitoring system by addressing the issue of log outputs. With the changes implemented, logs can now be simultaneously displayed on the screen and written to log files. This dual logging approach enhances both the real-time monitoring and post-analysis capabilities of our system.
=> Fix(release-v3.5) Enhance Component Monitoring with Dual Logging to Screen and File

.github/workflows/pull-request.yml, .github/workflows/sync-release.yml, .github/workflows/sync.yml, scripts/lib/logging.sh
This PR helps optimize the building script for openim, providing build time and addressing some CI/CD error issues.
=> fix: fix openim-server scripts and optimize build date

build/images/openim-rpc-encryption/Dockerfile, build/images/openim-rpc-extend-msg/Dockerfile, scripts/install-im-server.sh, scripts/lib/release.sh, scripts/make-rules/image.mk, scripts/release.sh
<br>
/kind feature
his PR addresses the automation issues in the advanced version of openim's CICD, serving as a foundational support for future GitOps implementation. This contribution is expected to have a significant impact and resolves the functionality of 'make release' in the advanced version.
=> feat: Enhanced Automation for OpenIM Advanced CICD and GitOps Support

.github/workflows/pull-request.yml
<br>
/kind feature
This PR addresses issues related to the process of release publishing. It introduces solutions that enhance our CI/CD pipeline, ensuring that automated bots can perform code formatting and submit daily PRs to maintain code quality and consistency.
=> feat: add pull request set workflows

internal/push/push_to_client.go
=> fix duplicated offline push

deployments/templates/env-template.yaml
<br>
/kind feature
fix(docker-compose): Update the env template to uncomment the mongo port
=> fix(docker-compose): Update the env template to uncomment the mongo port

docs/contrib/offline-deployment.md
assist with addressing the offline deployment issue for openim
=> Update offline-deployment.md openim offine deployment docs

docs/contrib/environment.md
assist in addressing the naming issue for openim in this PR
=> Update environment.md fix environment mongo username

docs/contrib/environment.md
=> docs: fix environments minio document parameter errors

pkg/common/startrpc/start.go
<br>
/kind bug
Fixed script problems in OpenIM
=> fix(main): fix openim scripts start rpc log 

scripts/lib/util.sh
This PR introduces the implementation of a graceful shutdown mechanism for our Go application. The goal is to ensure that the application can terminate gracefully, handling all in-flight requests without abruptly closing connections or losing data.
In the context of deploying updates or responding to critical issues, it's essential to minimize downtime and ensure a smooth transition without impacting the user experience. A graceful shutdown process allows the application to complete essential tasks, such as finalizing requests and releasing resources properly, before shutting down.
- **Signal Handling**: The application now listens for interrupt signals (SIGINT) and termination signals (SIGTERM) to initiate the shutdown process.
- **Shutdown Hooks**: Implemented shutdown hooks that are …
=> Implement Graceful Shutdown for Go Application

.github/workflows/golangci-lint.yml, .github/workflows/openimci.yml, docs/readme/README-JP.md
<br>
documentation
Fixes #1891
add README.md -JP
=> docs: add README.md JP

docs/readme/README-TR.md
<br>
documentation
Fixes #1900
add README.md-TR
=> docs: add README.md-TR

docs/readme/README-KR.md
<br>
documentation
Fixes #1895
add READ.md -KR
=> docs: add README.md -KR

docs/readme/README-ES.md
=> docs: add README-ES

docs/readme/README-FR.md
=> docs: add README.md -FR

docs/readme/README_hu.md
This PR adds a `README_hu.md` file, translating the existing `README.md` into Hungarian. By doing so, we aim to make the documentation more accessible to Hungarian-speaking users, thus extending the project's reach and inclusivity.
Introducing the Hungarian translation is a step towards our commitment to making the project accessible to a wider audience.
Fixes #
I encourage the review of the Hungarian translation for its accuracy and clarity. Any feedback or suggestions for improvement would be greatly appreciated to ensure the highest quality and accessibility of our documentation.
Please compare the `README_hu.md` with the original `README.md` to verify the accuracy and completeness of the translation. It's important to check for any formatting issues or discrepancies in the technical …
=> docs:add README_hu.md

docs/readme/README_fa.md
This PR introduces a `README_fa.md` file, translating the original `README.md` into Persian. This translation is aimed at making our documentation accessible to Persian-speaking users, further broadening the inclusivity and reach of our project.
The addition of the Persian translation underscores our commitment to diversity and inclusivity, ensuring that our project is welcoming and accessible to a wider global audience.
Fixes #
The Persian translation has been carefully prepared to ensure accuracy and clarity. Feedback and suggestions for further refinement are highly welcomed to guarantee that we meet the quality and accessibility standards of our documentation.
To verify the changes, reviewers are encouraged to compare the `README_fa.md` with the original `README.md` for translation …
=> docs:add README_fa.md

README.md
<br>
documentation
Fixes #
add community
=> docs: README add community

README.md, docs/readme/README_vi.md
=> add Docs/readme vi

docs/readme/README_el.md
=> add docs/README_el

tools/formitychecker/checker/checker.go
=> fix function name on comment

README.md
<br>
documentation
Fixes #
modify README Twitter
=> docs: modify README Twitter

internal/msggateway/client.go, internal/msggateway/long_conn.go, internal/msggateway/n_ws_server.go, internal/msggateway/user_map.go, internal/msgtransfer/init.go, internal/msgtransfer/online_history_msg_handler.go
=> Fix lint errors in modified code

README.md
<br>
documentation
Fixes #
update README Community
=> docs: update README Community

pkg/common/cmd/msg_utils.go, pkg/common/convert/friend.go, pkg/common/db/cache/conversation.go, pkg/common/db/controller/auth.go, pkg/common/db/controller/conversation.go, pkg/common/db/controller/msg.go, pkg/common/db/s3/cont/controller.go, pkg/common/db/s3/cos/cos.go, pkg/common/db/s3/minio/minio.go
=> Fix lint errors in modified code 

pkg/common/cmd/msg_utils.go, pkg/common/db/controller/auth.go, pkg/common/db/s3/minio/minio.go, pkg/common/db/s3/minio/thumbnail.go, pkg/common/db/s3/oss/oss.go, pkg/common/db/unrelation/msg.go, pkg/rpcclient/notification/group.go, pkg/rpcclient/third.go, pkg/statistics/statistics.go
=> Fix lint errors in modified code in the /pkg directory

docs/contrib/go-code.md
This PR aims to improve the documentation for OpenIM by enhancing the clarity, comprehensiveness, and usefulness of the configuration settings and linters settings sections. The current documentation provides a solid foundation, but there are opportunities to refine and expand upon it to better serve users.
**Changes Proposed:**
1. **Clarification of Configuration Options:** Additional explanations and examples will be provided for configuration options such as `skip-dirs` and `skip-files` to help users understand their usage and impact on the analysis process better.
2. **Expansion on Linters Settings:** Each linter setting will be elaborated on to provide users with a deeper understanding of their purpose and practical implications. This will include rationale behind each setting and …
=> Enhance Documentation for OpenIM Configuration and Linters Settings

scripts/install/test.sh
<br>
Fix #1981
Key highlights of 'RP' include:
1. **Seamless Integration**: 'RP' seamlessly integrates with existing testing workflows, allowing developers to incorporate it into their projects with ease.
2. **Efficiency and Speed**: By harnessing the efficiency of `make test`, 'RP' drastically reduces the time and effort required for bug identification and resolution.
3. **Precision Debugging**: 'RP' empowers developers with granular insights into API behavior, facilitating precise debugging and error resolution.
4. **Enhanced Reliability**: With 'RP', developers can have confidence in the reliability of their APIs, knowing that bugs are swiftly identified and rectified.
5. **Community Collaboration**: Built on the principles of community collaboration, 'RP' fosters an environment where …
=> fix: Revolutionary Bug Fixes in API Testing with 'RP': Solving Glitches with the Power of 'make test'

README.md
=> docs: update openim server readme github codespaces

.golangci.yml
<br>
/kind feature
Could you please assist in reviewing the changes made in this PR? It involves modifications to the .golangci yaml file, including the addition and removal of certain linters. Thank you for your help!
Fixes #1988
For crafting a Pull Request (PR) description that corresponds to the changes in the `.golangci.yml` configuration, here's a suggested format. This PR description aims to clearly communicate the rationale behind the changes, what has been changed, and the expected impact on the project:
---
This PR introduces several updates to the `.golangci.yml` configuration to enhance the efficiency and effectiveness of our linting process. These changes aim to refine the focus of our linters, adjust linting rules to better suit our coding standards, and improve the overall …
=> feat:  Update .golangci.yml Configuration for Improved Linting Efficiency

internal/msgtransfer/init.go, internal/rpc/friend/black.go, internal/rpc/friend/friend.go, internal/rpc/group/group.go, internal/rpc/msg/as_read.go, internal/rpc/msg/revoke.go, internal/rpc/msg/send.go, internal/rpc/msg/server.go, internal/rpc/third/s3.go, internal/rpc/third/third.go, internal/rpc/user/user.go
<br>
Fixes #1977
Change back to err name
=> Change back to err name

internal/rpc/group/group.go, internal/rpc/third/s3.go, internal/rpc/third/third.go, internal/rpc/user/user.go, pkg/common/db/cache/meta_cache.go, pkg/common/db/cache/msg.go, pkg/common/db/mgo/object.go, pkg/common/db/mgo/user.go, pkg/common/db/s3/minio/image.go, pkg/common/db/unrelation/mongo.go, pkg/common/discoveryregister/direct/directconn.go, pkg/rpcclient/msg.go, tools/up35/pkg/pkg.go
=> fix: wrap the error of group user and thrid

internal/rpc/group/group.go, internal/rpc/third/s3.go, internal/rpc/third/third.go, internal/rpc/user/user.go, pkg/common/db/cache/meta_cache.go, pkg/common/db/cache/msg.go, pkg/common/db/mgo/object.go, pkg/common/db/mgo/user.go, pkg/common/db/s3/minio/image.go, pkg/common/db/unrelation/mongo.go, pkg/common/discoveryregister/direct/directconn.go, pkg/rpcclient/msg.go, scripts/install/openim-api.sh, scripts/install/openim-crontask.sh, scripts/install/openim-msggateway.sh, scripts/install/openim-msgtransfer.sh, scripts/install/openim-push.sh, scripts/install/openim-rpc.sh, scripts/lib/logging.sh, scripts/lib/util.sh, scripts/start-all.sh, tools/up35/pkg/pkg.go
=> Optimize logs

internal/rpc/group/group.go, pkg/rpcclient/notification/group.go
=> fix: remove unnecessary error handling to avoid sending nil resp.

scripts/check-all.sh, scripts/docker-start-all.sh, scripts/lib/logging.sh, scripts/start-all.sh
=> Optimizing Docker Log Output Detection

scripts/check-all.sh, scripts/docker-start-all.sh, scripts/lib/logging.sh, scripts/lib/util.sh, scripts/start-all.sh
=> Optimizing Docker Log Output 

internal/rpc/third/third.go, pkg/common/db/mgo/object.go, pkg/rpcclient/msg.go, scripts/check-all.sh, scripts/docker-start-all.sh, scripts/lib/logging.sh, scripts/lib/util.sh, scripts/start-all.sh
=> Exit with code 1 when the check script fails

scripts/check-all.sh, scripts/install/openim-tools.sh, scripts/start-all.sh, tools/component/component.go
=> Execute after the component check succeeds && minio.Enable is not configured to use MinIO

scripts/install/openim-tools.sh
=> Log redirection causes incorrect program exit status.

scripts/check-all.sh, scripts/lib/util.sh
=> Fix bug Remove duplicate function definitions

tools/component/component.go
=> delete log for update images

scripts/docker-start-all.sh
=> Run in the background

Dockerfile, build/images/openim-api/Dockerfile, build/images/openim-cmdutils/Dockerfile, build/images/openim-crontask/Dockerfile, build/images/openim-msggateway/Dockerfile, build/images/openim-msgtransfer/Dockerfile, build/images/openim-push/Dockerfile, build/images/openim-rpc-auth/Dockerfile, build/images/openim-rpc-conversation/Dockerfile, build/images/openim-rpc-friend/Dockerfile, build/images/openim-rpc-group/Dockerfile, build/images/openim-rpc-msg/Dockerfile, build/images/openim-rpc-third/Dockerfile, build/images/openim-rpc-user/Dockerfile, build/images/openim-tools/component/Dockerfile, build/images/openim-tools/openim-web/Dockerfile
fix docker file images proxy
[![Docker Buildx Images CI](https://github.com/openimsdk/open-im-server/actions/workflows/docker-buildx.yml/badge.svg)](https://github.com/openimsdk/open-im-server/actions/workflows/docker-buildx.yml)
=> fix: fix docker file images proxy

internal/rpc/msg/verify.go
=> optimization: message remove options.

internal/rpc/conversation/conversaion.go, tools/component/component.go
=> fix: conversation crash caused by non-existence

scripts/check-all.sh, scripts/lib/util.sh
=> The check script is not compatible with Mac.

deployments/templates/env-template.yaml
<br>
This PR addresses a specific path resolution error encountered during the initialization process of the OpenIM server project, particularly affecting the generation of the `.env` file from its template. The issue leads to an incorrect path computation, resulting in a failure to generate or overwrite the `.env` file located in the project's root directory, while other configuration files in subdirectories are handled without issue. This fix ensures uniform handling of both root and subdirectory path resolutions, enabling a seamless initialization and setup process for all project configuration files, including those at the root level.
Fixes #2127
=> Fix Path Resolution Error for Root Directory .env File Generation Update env-template.yaml

.github/workflows/bot-auto-cherry-pick.yml, .github/workflows/milestone.yml
<br>
/kind feature
Could you please assist in reviewing the PR that addresses the cherry pick?
=> feat: set git cherry pick and Milestone

deployments/templates/env-template.yaml
<br>
This PR addresses a specific path resolution error encountered during the initialization process of the OpenIM server project, particularly affecting the generation of the `.env` file from its template. The issue leads to an incorrect path computation, resulting in a failure to generate or overwrite the `.env` file located in the project's root directory, while other configuration files in subdirectories are handled without issue. This fix ensures uniform handling of both root and subdirectory path resolutions, enabling a seamless initialization and setup process for all project configuration files, including those at the root level.
Fixes #2127
=> releasev3.6: Automated cherry pick of #2128 upstream release v3.6

README.md
=> update release-v3.1  images

README.md
feat: update release-v3.2 images
=> feat: update release-v3.2 images 

.github/workflows/e2e-test.yml, .github/workflows/golangci-lint.yml, .github/workflows/openimci.yml
=> update some ci file

.env, .github/workflows/e2e-test.yml
=> use openim/openim-admin openim/openim-web image

README.md
=> auto close issue test

.env
=> update web/admin front image

go.mod, go.sum
If there are uppercase letters in the directory, 'mage start' encounters an error
Fixes #2251
=> fix bug:If there are uppercase letters in the directory, 'mage start' encounters an error

pkg/common/config/config.go
(cherry picked from commit 480ccc70b0512219f98913ac02550f3a77586254)
Fixes #2262
=> fix: minio config url recognition error

docker-compose.yml, go.mod, go.sum, internal/tools/cron_task.go, magefile.go, tools/check-component/main.go
=> Skip minio check 

docker-compose.yml, go.mod, go.sum, internal/tools/cron_task.go, magefile.go, tools/check-component/main.go
=> Skip minio check

config/openim-rpc-third.yml, go.mod, go.sum, internal/msgtransfer/online_history_msg_handler.go, internal/msgtransfer/online_msg_to_mongo_handler.go, internal/push/push_handler.go, pkg/common/db/mgo/msg.go
=> fix: s3 config

internal/msgtransfer/online_history_msg_handler.go
=> fix: main bug fix notification unread

internal/rpc/msg/send.go
=> fix: at group message.

scripts/mongo-init.sh
=> Add a retry mechanism to mongo init

internal/push/offlinepush/fcm/push.go
Fixes #2331
fix:FCM push failed will return error
=> fix:FCM push failed will return error

internal/rpc/auth/auth.go, pkg/common/storage/cache/redis/token.go, pkg/common/storage/cache/token.go, pkg/common/storage/controller/auth.go
Fixes #2351
fix:create auth token can add expire time
=> fix:create auth token can add expire time

internal/api/msg.go, pkg/apistruct/manage.go
Fixes #2368
Fix: message can store ex
=> fix: message can store Ex (#2371)

pkg/common/storage/cache/redis/seq.go, pkg/rpccache/conversation.go
Fixes #2375
Optimize get conversation seq
=> Optimize get conversation seq

pkg/common/storage/database/mgo/msg.go
=> fix: remove repeat append logic in search message.

internal/msggateway/client.go
chore: add ping Handler DEBUG log in msgGateway.
=> chore: add ping Handler DEBUG log in msgGateway.

config/alertmanager.yml, config/grafana-template/Demo.json, config/instance-down-rules.yml, internal/rpc/user/user.go, pkg/common/prommetrics/grpc_user.go, pkg/common/prommetrics/rpc.go
=> Feat metrics

config/email.tmpl, internal/rpc/third/log.go, pkg/common/storage/controller/user.go
=> Fix search log

.github/workflows/build-docker-image.yml, .github/workflows/openimci.yml
=> fix: rm e2e in ci

pkg/rpcclient/msg.go
=> fix: fill notification offlinePush by config

go.mod, go.sum
* feat: update go mod pkg to latest.
* revert tool pkg version.
Fixes #
=> chore: revert tool pkg version. (#2476)

config/grafana-template/Demo.json
Fixes #
feat: update grafana template
=> feat: update grafana template

pkg/common/storage/controller/friend.go
=> fix: import del cache

pkg/rpcclient/friend.go
=> fix:update recive name to same

pkg/apistruct/msg.go
Fixes [#2498](https://github.com/openimsdk/open-im-server/issues/2498)
fix: fix-validate message.
=> fix: fix-validate message.

internal/rpc/msg/callback.go, pkg/callbackstruct/common.go
Fixes https://github.com/openimsdk/open-im-server/issues/2500
feat:add message send time in callback
=> feat:add message send time in callback

pkg/rpcclient/msg.go
=> fix:get msg error

pkg/common/storage/database/mgo/user.go
=> fix:mgo delete err

tools/url2im/pkg/manage.go
=> fix:doPut error

internal/rpc/conversation/conversaion.go
Fixes #2563
Fix set conversation error.
=> Fix set convsation

internal/msggateway/encoder.go, internal/msggateway/encoder_test.go
feat: implement no gob encoder.
=> feat: implement no gob encoder.

pkg/localcache/lru/lru_lazy.go
=> fix: lru lock

config/openim-msgtransfer.yml, config/openim-push.yml, config/prometheus.yml, internal/rpc/group/callback.go
Fixes #2642
fix: kick group member callback
=> fix: kick group member callback

internal/api/router.go
Fixes #2649
fix: user register route
=> fix: route

internal/rpc/group/db_map.go
=> fix: fix update groupName invalid.

config/webhooks.yml, pkg/common/storage/controller/auth.go
=> fix: admin token

config/discovery.yml, docker-compose.yml, internal/msggateway/online.go
Fixes #2520
Fix online and offline webhook.
Remove zk.
=> Line webhook

pkg/rpcclient/auth.go
Fixes #
package auth import twice
=> fix: auth package import twice

internal/rpc/group/group.go
Fixes #2728
fix: group level change logic
=> fix: change update group member level logic

internal/push/offlinepush/offlinepusher.go
Fixes #2774
Push configuration can ignore case sensitivity
=> feat: Push configuration can ignore case sensitivity

.github/workflows/cleanup-after-milestone-prs-merged.yml, .github/workflows/merge-from-milestone.yml
=> feat: implement merge milestone PR to target-branch.

.github/workflows/go-build-test.yml, .github/workflows/merge-from-milestone.yml
=> build: improve workflows logic.

internal/rpc/group/group.go
=> fix: improve time condition check mehtod.

internal/push/callback.go
Fixes #2715
fix: webhook before online push
=> fix: webhook before online push

internal/rpc/group/group.go
=> fix: improve condition check.

pkg/common/storage/cache/redis/msg.go, pkg/common/storage/controller/msg.go
=> fix: Write back message to Redis

internal/msggateway/client.go
=> fix: ws write io timeout

internal/rpc/conversation/conversation.go
Fixes #2830 #2809
fix: SetConversations can update new conversation
=> fix: SetConversations can update new conversation

config/openim-push.yml, deployments/templates/config.yaml, docs/contrib/environment.md, internal/push/offlinepush/jpush/body/notification.go, internal/push/offlinepush/jpush/push.go, pkg/common/config/config.go
=> fix #2860 migrate jpns to jpush

internal/rpc/msg/as_read.go, internal/rpc/msg/seq.go, pkg/common/storage/controller/msg.go
=> fix: Wrong Redis Error Check

pkg/common/storage/cache/redis/conversation.go
Fixes #
fix minor log typo, nothing else changed.
=> fix: minor log typo

internal/rpc/msg/as_read.go
=> fix: webhookAfterSingleMsgRead will be called correctly

internal/rpc/msg/send.go, internal/rpc/msg/verify.go
=> fix: webhookBeforeSendSingleMsg will call before black and friend check

pkg/common/storage/controller/msg.go
Fixes #2882
The message cache and the database are out of sync, so revert that commit.
=> revert: write msg to redis

.env
Fixes #3056
update: env image version
=> update: env image version

.env
=> fix: node exporter image

config/prometheus.yml, docker-compose.yml
=> Fix: prometheus config

pkg/common/storage/controller/auth.go
=> fix: check error in BatchSetTokenMapByUidPid

.github/workflows/docker-build-and-release-services-images.yml, .github/workflows/go-build-test.yml, .github/workflows/merge-from-milestone.yml, .github/workflows/publish-docker-image.yml
=> build: improve workflows contents.

.github/workflows/merge-from-milestone.yml
=> build: keep conflict is true.

.github/workflows/merge-from-milestone.yml
=> fix: solve workflows stop when merge failed

internal/push/offlinepush/fcm/push.go, internal/push/offlinepush/getui/body.go, internal/push/offlinepush/getui/push.go, pkg/common/storage/cache/redis/lua_script.go
* fix: offline push can display badge
* feat: strategy
* feat: log
* feat: log
* chore: offlinepush
* fix: offlinepush
* fix: log
(cherry picked from commit 14393b0f5316aa35d1949bcafd0e73afe0263560)
Fixes #
=> fix: Offline push does not have a badge && Android offline push (#3146)

internal/rpc/msg/verify.go, pkg/authverify/token.go
=> feat: system account send msg doesn't need friend verify

internal/rpc/group/group.go, internal/rpc/group/notification.go
=> fix: solve uncorrect GroupMember enter group notification type.

internal/rpc/conversation/conversation.go, internal/rpc/conversation/db_map.go
=> refactor: improve setConversations method.

internal/rpc/group/group.go
=> fix: solve unocrrect invite notification

internal/api/config_manager.go, internal/api/router.go, pkg/apistruct/config_manager.go
=> feat: set configs api

.github/workflows/go-build-test.yml, internal/rpc/user/user.go, pkg/common/servererrs/code.go, pkg/common/servererrs/predefine.go
=> feat: check if the secret in config/share.yml has been changed during registration

internal/rpc/group/group.go
Fixes https://github.com/openimsdk/openim-sdk-core/issues/910
=> fix: group status in GroupDismissedNotification

tools/stress-test-v2/main.go, tools/stress-test/main.go
=> feat: Implement stress test v2.

tools/seq/internal/seq.go
=> fix: data version SetVersion will add record

go.mod, go.sum, internal/api/router.go, internal/msggateway/ws_server.go, internal/msgtransfer/online_msg_to_mongo_handler.go, internal/push/push_handler.go, internal/rpc/user/user.go, pkg/authverify/token.go, pkg/common/startrpc/start.go, pkg/common/startrpc/tools.go, pkg/rpccache/online.go
=> fix: standalone mode cannot be used

internal/api/msg.go, internal/api/router.go, internal/rpc/msg/send.go
=> fix: send simple msg

pkg/common/config/config.go
=> fix redis config db field

internal/tools/cron/cron_task.go, internal/tools/cron/dist_look.go, start-config.yml
=> feat: support distributed lock in crontask.

Dockerfile
=> build: update gomake version in dockerfile.[Patch branch]

internal/rpc/relation/friend.go, internal/rpc/relation/notification.go
=> fix: import friends send notification

internal/rpc/relation/friend.go
=> fix: Add friend DB in notification sender

internal/rpc/conversation/conversation.go
=> fix: solve `createTime` not set in setConversation and Create Conversation.

.github/workflows/update-version-file-on-release.yml, version/version.go
=> fix: remove update version file workflows have new line in 3.8.3-patch branch.

internal/rpc/third/third.go
=> fix: s3 aws init

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/other.yml, .github/workflows/auto-invite-comment.yml, .github/workflows/help-comment-issue.yml, .github/workflows/user-first-interaction.yml, README.md, README_zh_CN.md, docs/readme/README_cs.md, docs/readme/README_da.md, docs/readme/README_el.md, docs/readme/README_es.md, docs/readme/README_fa.md, docs/readme/README_fr.md, docs/readme/README_hu.md, docs/readme/README_ja.md, docs/readme/README_ko.md, docs/readme/README_tr.md, docs/readme/README_uk.md, docs/readme/README_vi.md, install.sh
=> docs: update slack link.

internal/api/msg.go, pkg/apistruct/msg.go
=> fix: added AtUserIDList to the @ message for API sending.

pkg/common/storage/controller/msg.go, pkg/common/storage/model/msg.go
=> fix: solve batch incorrect error in Find DocIDs

config/mongodb.yml, go.mod, go.sum, pkg/common/config/config.go
=> feat: support mongo replicaset mode.

config/README.md, config/README_zh_CN.md
=> docs: update readme of config file.

go.mod, go.sum, internal/msgtransfer/init.go, internal/msgtransfer/online_history_msg_handler.go, internal/msgtransfer/online_msg_to_mongo_handler.go, internal/push/push.go
=> fix: performance issues with Kafka caused by encapsulating the MQ interface

internal/rpc/relation/friend.go, internal/rpc/relation/notification.go
=> fix: import friends send notification in v3.8.3-patch

internal/api/router.go, pkg/common/storage/cache/redis/token.go
* fix: performance issues with Kafka caused by encapsulating the MQ interface
* fix: admin token in standalone mode
(cherry picked from commit d817cb0ffd4ad9c540a36b358c71c081e800920b)
Fixes #
=> fix: admin token in standalone mode (#3499)

pkg/common/storage/cache/mcache/msg_cache.go, pkg/localcache/cache.go, pkg/localcache/lru/lru_lazy.go, pkg/localcache/lru/lru_slot.go, pkg/rpccache/online.go
=> fix: optimize to lru  local cache.

docker-compose.yml
=> feat: enable redis aof-use-rdb-preamble && disable auto rdb

docker-compose.yml
=> build: comment admin services.

.env
=> fix: switch kafka & etcd image namespace to bitnamilegacy in pre-release-v3.8.4 branch.

internal/rpc/conversation/conversation.go
=> fix: GetSortedConversationList nil pointer when chatlog not found in v3.8.3-patch branch.

pkg/msgprocessor/conversation.go
=> Fix: Resolved the issue of incorrect generation of conversationID in 3.8.3-patch branch.
