openimsdk/open-im-server

- pkg/common/db/mysql.go
在服务初始化mysql数据表时报错，提示`group_id`,`uid`等字段联合索引超过长度限制，无法创建新表。
> fix :mysql index field is too long, resulting in table creation failure

- .gitignore
- config/config.docker.yaml
- deploy.Dockerfile
- docker-compose.yaml
- script/docker_check_service.sh
使用独立内部网络以及修改container名称以避免重复，减少部署出错的可能性。fix #70
> use independent network and modify container names

- internal/api/group/group.go
管理员创建群组时传过来的ownerUserID,可能和token里解析的不一致，如果params里OwnerUserID不为空，则应该以传入的为主
> 管理员创建群组bug fix

- internal/rpc/msg/verify.go
> fix:sent message already has a timestamp, no timestamp will be generated

- internal/msggateway/client.go
<br>
remove redundant set read deadline, it has set for conn before.
Fixes #1028
> feat: remove redundant read deadline in gateway

- internal/msgtransfer/persistent_msg_handler.go
<br>
/kind bug
see #1009 
Fixes #1009
> internal/msgtransfer: fix unreachable code issue

- scripts/install/openim-msggateway.sh
- scripts/install/openim-msgtransfer.sh
- scripts/lib/util.sh
<br>
/kind feature
This PR introduces an enhancement to the shell script responsible for managing the file descriptor limit of the process. This is crucial for applications that require handling numerous simultaneous file operations, ensuring smooth performance without hitting the default system limit.
Changes included:
+ A new function `set_max_fd()` that dynamically sets the file descriptor limit based on user input and system maximum permissible values.
+ Conditional checks to ensure compatibility and appropriate handling for different operating systems (excluding Darwin and Cygwin due to their distinct management of file descriptors).
+ Warning messages to alert users when desired limits cannot be set, providing insights into potential issues.
+ An example usage of …
> fix: Implement Enhanced File Descriptor Limit Handling in Shell Script

- scripts/lib/color.sh
Replaced the `-v` operator with a more universally compatible method for variable checking in the bash script. The update uses parameter expansion to check if a variable is set, ensuring the script runs smoothly on environments with different Bash versions.
Issue: https://github.com/openimsdk/open-im-server/issues/1182
<br>
/kind bug
Fixes #1182
+ Updated the method used to check if a variable is set within the bash script. Previously, the `-v` operator was used which is not supported in some Bash versions, leading to an error in certain environments.
+ The use of the `-v` operator can lead to errors in environments using an older Bash version or different shells, hampering the script's reliability and portability.
+ Implementing a more universally compatible variable checking method …
> Ensure Script Compatibility Across Different Bash Versions

- README-zh_CN.md
- pkg/common/config/config.go
- pkg/common/db/cache/init_redis.go
In redis cluster mode, we only need a dns lb resolver redis cluster address, that is, an address. Then the mapping of all slot-redis instances is obtained by metadata through the cluster protocol.
So a new parameter is added, clusterMode bool.
In addition, lint changed it a little bit as a lint.
Fix: #1186
> feat: add redis cluster mode in option

- pkg/common/db/localcache/group.go
The lock granularity here is a bit large, so two-stage locks are used and rpc io operations are handled independently to improve the throughput under cache miss.
Fix: #1186
> optimize: reduce lock latency for localcache group

- internal/rpc/group/callback.go
<br>
This PR is updated a field.
#1191
> bug:update a filed

- pkg/common/db/localcache/conversation.go
The lock granularity here is a bit large, so two-stage locks are used and rpc io operations are handled independently to improve the throughput under cache miss.
> optimize: reduce lock latency for conversation cache

- pkg/common/db/relation/mysql_init.go
- pkg/common/db/relation/mysql_init_test.go
<br>
/kind bug
It will failed when you init app with a custom database name which contains '-' (eg: "im-db").
```
Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-db default charset utf8mb4 COLLATE utf8mb4_unicode_ci' at line 1
[0.236ms] [rows:0] CREATE DATABASE IF NOT EXISTS im-db default charset utf8mb4 COLLATE utf8mb4_unicode_ci;
```
Screenshot:
Fixes #
* Added a new test.
* Added a new type `option`.
* Note `defer sqlDB.Close()` has been moved.
`go test -run ^TestMaybeCreateTable$ github.com/openimsdk/open-im-server/v3/pkg/common/db/relation`
> fix: create database name

- internal/push/push_to_client.go
I have read the CLA Document and I hereby sign the CLA
> fix: NotNotifyUser receive offline push

- internal/msggateway/n_ws_server.go
1. reduce register client latency.
2. go1.19 support atomic type.
> perf: reduce register client latency

- pkg/common/db/relation/conversation_model.go
> fix: wrong column

- internal/msggateway/client.go
- internal/msggateway/context.go
- internal/rpc/msg/message_interceptor.go
- pkg/msgprocessor/conversation.go
<br>
/kind cleanup
This PR improves some of the details of the code.
clean up the code
Fixes #
I suggest reading the corresponding code for better understanding.
There are several methods to verify the health of this PR:
Local verification by fetching my PR through gh or git.
Verification through CICD.
Local verification by running make start.
> Details optimization

- pkg/common/db/controller/conversation.go
修复SuperGroupRecvMsgNotNotifyUserIDs缓存不更新
> fix: del SuperGroupRecvMsgNotNotifyUserIDs cache when conv edit

- internal/msggateway/client.go
- internal/msggateway/message_handler.go
1. Refactor the client.go code. 
2. A sync.pool object pool has been added for high-frequency req structs. Although the current code uses the value object of req, subsequent operations such as decode and replyMessage cause the object to escape to the heap. This means that during compilation, the object has already been determined to be allocated on the heap. Therefore, since this object is a heap object, pointers can be used directly afterwards, as stack allocation and copying also have their costs. Furthermore, it's only when the req does not escape that it's allocated on the stack.
Since it's a heap object, using sync.pool for object pooling can reduce the overhead of garbage collection.
> refactor: client in msggateway

- internal/push/offlinepush/dummy/push.go
- internal/push/push_to_client.go
> feat: use dummy pusher by default

- internal/rpc/group/group.go
> fix: GetUserReqApplicationList dismissed group error

- internal/push/push_to_client.go
lower the level of code nesting for push/push_to_client.go.
> refactor: lower the level of code nesting

- pkg/common/config/config.go
- pkg/common/kafka/producer.go
Allows users to select parameters. 😁
The default waitforall is slow because it needs to wait synchronously for the brokers of the isr cluster to synchronize data.
Kafka's compression  can appropriately reduce storage in kafka and pod/node bandwidth.
Of course, the effectiveness of parameters still depends on the scenario.
> fix: add kafka compress type and producer ack params

- pkg/common/config/config.go
- pkg/common/db/cache/msg.go
- pkg/common/db/cache/msg_test.go
1. 增加 `enablePipeline` 配置，用户可以选配来开启 redis pipeline 模式. `go-redis` 库包是支持在集群模式下，pipeline 下不同key 的拆离并发操作，但这毕竟是 sdk 层实现，对于容错的处理有限，多数场景是够用了。
2. 当不开启 pipeline 模式下，以前为串行同步执行逻辑，现在为有限并发模式，内部通过索引使其返回结果有序。
3. 补全了这两个方法集的单元测试。
暂时先写 set/get 这两个方法，后面有空继续优化。😁
> perf: add concurrency and pipeline for redis cache

- pkg/common/ginprometheus/ginprometheus.go
1.  if don't close http.response.body, throw resource leak.  ( goroutine leak and fd leak)
2. replace io.ReadAll to io.ioutil, `io.ioutil` is deprecated in go1.16.
3. use gin.context.FullPATH, because gin.Request.URL.PATH is full url with query params.  e.g. prometheus only need to record `/article/:uid` url, don't need `/article/13183?page_index=10&page=100&q=xxx&order=desc`.  when the url is randomized, this design is not friendly to prome storage and does not display well in grafana.
4. refactor the code.
> refactor: gin prometheus for api

- internal/msggateway/n_ws_server.go
notify client info to nodes concurrently on register.
1.  remove unused hubServer object.
2. format `some code`
3. format `import package`
4. err lint.
> perf: notify nodes concurrently on register

- internal/msgtransfer/init.go
- internal/msgtransfer/online_history_msg_handler.go
1. reduce lock for sarama.Value.
2. refactor some code.
3. record push queue duration.
> fix: reduce lock msg transfer

- internal/tools/cron_task.go
- internal/tools/cron_task_test.go
- internal/tools/msg_doc_convert.go
- pkg/common/config/config.go
- pkg/common/db/cache/init_redis.go
1. 重构了 cron_task 的启动代码, 加入了信号处理.
2. 通过分布式锁来实现 crontask 服务在分布式环境并发执行多次的问题。
> 通常为了 HA，cron 服务会多实例部署，但 cron 注册的任务同一时间只需要执行一次即可，无需多个实例执行。 
😁 (如果不需要这个分布式功能，我可以 reset 掉 )
> refactor: crontask cmd

- internal/msggateway/init.go
- internal/msggateway/long_conn.go
- internal/msggateway/n_ws_server.go
- internal/msggateway/options.go
- pkg/common/config/config.go
control write buffer size of ws conn. the default value is 4kb. if the network quality of im client is poor (e.g. use mobile 3g, moving at high speed), we can increase the buffer size appropriately. 
In addition, a lot of data is written to the socket, when the socket write buffer is full, it can also cause blocking.
In short, we can scale up the memory as needed.
> perf: control ws write buffer

- pkg/common/db/cache/msg.go
- pkg/common/db/cache/msg_test.go
pervent redis block when use `keys *` command to request redis.
1. replace redis.keys to redis.scan.
2. the redis of many companies don't support the keys command, Or deny keys command.
> perf: redis block with keys command

- scripts/install/test.sh
docs: add openim search test
openim api test
```
make test-api
```
> [!WARNING]
> I am in the process of migrating the API testing to the "test/" directory.
> docs: add openim search test

- docs/CODEOWNERS
add @rfyiamcool ID to code_owers.
> docs: add rfyiamcool to code_owners

- config/templates/README.md
- config/templates/alertmanager.yml.template
- config/templates/config.yaml.template
- config/templates/env.template
- config/templates/prometheus.yml.template
- deployments/templates/env-template.yaml
- docker-compose.yml
- docs/contrib/util-makefile.md
- scripts/init-config.sh
<br>
/kind feature
I would greatly appreciate it if you could assist us in improving the design of the Docker Compose startup process, as well as automating it and implementing environment variable retrieval.
Link: #1514, #1513, #1504
> feat: add openim docker compose and env

- .github/workflows/openimci.yml
- config/templates/config.yaml.template
- config/templates/env.template
- deployments/templates/env-template.yaml
- docker-compose.yml
- docs/contrib/environment.md
- scripts/check-all.sh
- scripts/docker-start-all.sh
- scripts/init-config.sh
- scripts/install/environment.sh
- scripts/lib/logging.sh
- scripts/lib/util.sh
<br>
/kind feature
**Body:**
This PR addresses critical issues faced by users when deploying OpenIM on macOS, providing necessary fixes and improvements to streamline the deployment process.
**Key Highlights:**
1. **macOS Deployment Issues Resolved:**
- We identified that some users were encountering challenges while deploying OpenIM on macOS. This update includes adjustments and optimizations specifically targeting the macOS environment, ensuring a smoother deployment experience.
2. **Make Check for Port Availability:**
- Previously, the `make check` command encountered difficulties in correctly identifying and displaying available ports. This PR introduces a refined approach to port checking, enhancing the accuracy and reliability of the process.
3. **Integration of CI/CD Logic for …
> feat: support mac deployment and optimization make check

- pkg/common/discoveryregister/discoveryregister.go
> support multipe msggateway services in k8s deployments

- tools/component/component.go
> fix: fix the output format

- deployments/templates/openim.yaml
- docs/contrib/environment.md
- go.mod
- go.sum
- internal/api/friend.go
- internal/api/msg.go
- internal/api/route.go
- internal/api/user.go
- internal/rpc/friend/friend.go
- internal/rpc/user/user.go
- pkg/apistruct/msg.go
- pkg/authverify/token.go
- pkg/common/config/config.go
- pkg/common/db/controller/user.go
- pkg/common/http/http_client.go
- pkg/rpcclient/user.go
- scripts/check-all.sh
- scripts/install/environment.sh
> feat: add the notificationAccount

- pkg/msgprocessor/options.go
- pkg/rpcclient/msg.go
> fix: add syncself for some notifications.

- .github/workflows/openimci.yml
- deployments/templates/env-template.yaml
- docker-compose.yml
- scripts/check-all.sh
- scripts/install/environment.sh
- tools/component/component.go
<br>
/kind feature
The issue addressed by this PR is the lack of clarity in the current make check results, causing confusion and uncertainty about the underlying reasons. Additionally, the current CI system is not sufficiently robust.
Fixes #1638
CICD 
local test
> fix: fix openim scripts and ci add openim check

- scripts/check-all.sh
<br>
This Pull Request addresses the compatibility issue in the print_services_and_ports function found in check-all.sh, enabling it to work with Bash versions older than 4.3. The solution involves removing the use of named references (local -n), which are not supported in older Bash versions.
Rewritten print_services_and_ports to accept arrays directly as arguments.
The function now handles service names and ports without relying on named references, ensuring compatibility with a broader range of Bash environments.
The modified script has been tested in environments with both older (pre-4.3) and newer versions of Bash.
All tests ensure that the function correctly prints services and their corresponding ports without errors.
Fixes #1642
While this change aims at increasing compatibility, …
> fix: Bash Compatibility in print_services_and_ports Function

- scripts/install-im-server.sh
Signed-off-by: Xinwei Xiong (cubxxw) <3293172751nss@gmail.com>
<br>
/kind bug
This PR addresses an issue in the deployment script where the script would not fail upon encountering errors during the `docker compose up -d` process. The modification ensures that the script checks the status of Docker containers immediately after they are started. If any container fails to start, the script will now output an error message and logs before exiting. This enhancement is crucial for maintaining the robustness and reliability of the deployment process.
Fixes a critical issue where the deployment script would not correctly report failures during the Docker container startup process.
Please note the added check after the `docker compose up -d` command, ensuring that any container startup failure is …
> feat: fix openim server install scripts

- build/goreleaser.yaml
<br>
I'm currently experiencing a problem with the GoReleaser Action v4 in our GitHub Actions workflow, specifically when releasing different types of versions. While pre-releases such as v3.5.1.beta.0 are being published successfully, the action encounters failures during the publishing of official releases (e.g., v3.5.1).
/kind feature
The issue is evident in the 'release actions' job of our workflow. Detailed information and logs can be found here: [Release Actions Job](https://github.com/openimsdk/chat/actions/runs/7364259821/job/20044473138)
Fixes #
> fix: rIssue with Asset Uploading for Official Releases in GoReleaser Action v4 - release openim version not auto build 

- internal/rpc/user/user.go
> fix: fix the search_notification_account api return result

- go.mod
- internal/rpc/group/group.go
> fix: dissmissGroup and lack of keyword bug

- pkg/rpcclient/notification/group.go
(cherry picked from commit 4c3c4555a35ec8e31ffbf3e96a5dba3bceec09ee)
<br>
Fixes #1739
> fix: GroupApplicationRejectedNotification not notification apply for userID

- internal/rpc/group/group.go
(cherry picked from commit 48ff03f854e48fd22819c818586c6385d899a3c1)
<br>
Fixes #1746
> fix: NotificationUserInfoUpdate not notified

- docker-compose.yml
Description:
This pull request (PR) addresses the need for stability by pinning specific Docker image versions in the docker-compose configuration for minio and openim-web services. By specifying the exact image versions, we ensure that the system operates consistently and minimizes any potential issues arising from image updates. This enhancement will contribute to a more reliable and predictable deployment environment for these services.
Key Changes:
- Docker Compose configuration files have been updated to include specific image version tags for minio and openim-web.
- The pinned image versions have been tested to ensure compatibility and stability within the compose environment.
- Documentation has been updated to reflect the new image version requirements.
> Stability Enhancement: Pin Docker Compose Images for minio and openim-web

- .devcontainer/devcontainer.json
- assets/colors.md
- pkg/common/config/parse.go
- pkg/util/flag/flag.go
- pkg/util/genutil/genutil.go
- pkg/util/genutil/genutil_test.go
- scripts/docker-start-all.sh
- scripts/install/openim-msgtransfer.sh
- scripts/install/openim-rpc.sh
- scripts/start-all.sh
<br>
This Pull Request introduces several enhancements to the existing scripts, adding support for MacOS deployment, and updating the documentation to reflect these changes. The key updates include:
1. **Script Optimization:** Improved the overall structure and readability of the scripts, making them more efficient and easier to maintain.
2. **MacOS Compatibility:** Extended support to MacOS by adding conditional statements to handle differences in command-line tools, especially the `ps` command, ensuring seamless functionality across both Linux and MacOS platforms.
3. **Documentation Improvements:** Updated the documentation to include instructions and notes on MacOS compatibility, providing clear guidance for users deploying on MacOS.
These enhancements not only make the scripts more …
> feat: Enhance Script Details and Add MacOS Compatibility with Documentation Updates

- docker-compose.yml
- docs/contrib/mac-developer-deployment-guide.md
<br>
/kind feature
This Pull Request introduces significant improvements to the process of deploying chat functionalities on Mac systems using containerization. The changes focus on streamlining the deployment process and enhancing the associated documentation to provide clearer guidance.
- **Containerized Deployment**: Implemented a containerized approach for deploying chat functionalities on Mac. This ensures a more consistent and isolated environment, reducing issues related to system dependencies.
- **Documentation Overhaul**: Revised and updated the deployment documentation to include specific instructions and clarifications for Mac users. This includes:
- Detailed steps for setting up the Docker environment on Mac.
- Instructions on modifying the `docker-compose` …
> feat: Enhance Mac Deployment for Chat with Containerization and Documentation Updates

- docs/README_ar.md
- docs/README_cs.md
- docs/README_da.md
- docs/README_de.md
- docs/README_el.md
- docs/README_eo.md
- docs/README_es.md
- docs/README_fa.md
- docs/README_fi.md
- docs/README_fr.md
- docs/README_hu.md
- docs/README_id.md
- docs/README_it.md
- docs/README_ja.md
- docs/README_ko.md
- docs/README_ml.md
- docs/README_nl.md
- docs/README_pl.md
- docs/README_pt_BR.md
- docs/README_ru.md
- docs/README_tr.md
- docs/README_ua.md
- docs/README_vi.md
- docs/README_zh_CN.md
- docs/README_zh_TW.md
Added README.md files in multiple languages
include:
Simplified Chinese, Traditional Chinese, Arabic, etc., a total of 25 languages.
Help improve accessibility and make it easier for contributors to join us.
> docs:Add multi-language README.md in ./docs/ file

- cmd/openim-api/main.go
- internal/msgtransfer/init.go
- internal/msgtransfer/online_history_msg_handler.go
- internal/msgtransfer/online_msg_to_mongo_handler.go
- internal/push/consumer_init.go
- internal/push/push_handler.go
- internal/push/push_rpc_server.go
- internal/rpc/msg/server.go
- internal/tools/cron_task.go
- internal/tools/msg.go
- pkg/common/db/cache/init_redis.go
- pkg/common/db/controller/msg.go
- pkg/common/db/mgo/conversation.go
- pkg/common/db/mgo/group.go
- pkg/common/db/mgo/group_member.go
- pkg/common/db/mgo/group_request.go
- pkg/common/db/mgo/user.go
- pkg/common/db/unrelation/mongo.go
- pkg/common/kafka/consumer_group.go
- pkg/common/kafka/producer.go
- pkg/common/startrpc/start.go
> fix: process add errors wrap.

- scripts/lib/logging.sh
- scripts/lib/util.sh
- scripts/start-all.sh
This PR introduces color logging for error messages in the `openim::log::error` function. By incorporating red color to the error logs, it aims to enhance readability and make it easier for developers to identify and debug errors in a sea of console output. The modification utilizes ANSI color codes to apply red color to both the initial error message and any subsequent messages passed to the function. This feature is implemented in a backward-compatible manner, ensuring that existing functionality remains unaffected while providing an optional visual cue for error logging.
Key Changes:
- Defined ANSI color codes for red and no color (reset) within the `openim::log::error` function.
- Applied these color codes to the error messages output to ensure they are displayed in red on compatible …
> feat: Add Color Logging for Error Messages

- .golangci.yml
- README.md
> Update readme and golangci lint

- scripts/install/openim-tools.sh
- scripts/start-all.sh
- tools/component/component.go
> Execute after the component check succeeds   && minio.Enable is not configured to use MinIO

- pkg/common/db/mgo/group.go
Add Descending Sort by Creation Time in Group Search] Optimize the sorting function of group search - According to the previous discussion, in order to improve the user experience when searching for groups, we need to add Descending Sort by Creation Time in Group Search at http:// Added a sorting function in descending order of creation time to the group search results of 14.29.213.197:50002/group/get_groups.  
This will help users find newly created groups faster and improve the way information is presented.
Fix: #2089
> fix: Add Descending Sort by Creation Time to Group Search & Fix Admin Update Error

- internal/rpc/group/cache.go
- internal/rpc/group/group.go
- internal/rpc/msg/sync_msg.go
- pkg/authverify/token.go
- pkg/rpcclient/group.go
<br>
/kind bug
This PR addresses a bug in the `SearchMessage` API where the member count for groups was incorrectly displayed as zero during automated testing and script execution. The root cause was identified as a lack of direct integration with the group member count retrieval in the search logic. To resolve this issue, we have modified the `SearchMessage` function to incorporate an accurate count of group members by leveraging the `GetGroupMemberIDs` method from the `GroupLocalCache`. This ensures the `GroupMemberCount` in the response accurately reflects the actual number of members in a group, enhancing both data accuracy and the effectiveness of automated tests. 
Changes include:
- Utilizing `GetGroupMemberIDs` to fetch the real member count for each group encountered in chat logs. …
> fix: Fix Incorrect Group Member Count in SearchMessage API  group getGroupMemberIDs is 0 err

- internal/rpc/msg/callback.go
> fix: Fix the callback after reading the group message

- docs/contrib/images.md
**Description:**
This PR introduces an optimization for users in China aiming to deploy OpenIM more efficiently. By default, the `.env` file generated after executing `make init` offers several options for the image registry, including GitHub, Docker Hub, and Ali Cloud. Recognizing the network latency and download speed challenges within China, this update highlights the recommendation of using the Aliyun image address for such users.
**Changes:**
- Updated the `.env` file template within the deployment scripts to emphasize the Aliyun registry (`registry.cn-hangzhou.aliyuncs.com/openimsdk`) as the recommended option for users in China.
- Added comments in the `.env` file to guide users on how to switch the `IMAGE_REGISTRY` variable to Aliyun for optimal download speeds.
- Provided …
> docs: Optimize Deployment Speed for Users in China with Aliyun Image Registry

- scripts/make-rules/golang.mk
The current Makefile restricts the project to specific Go versions: 1.19, 1.20, 1.21, 1.22, and 1.23. This limits the flexibility of the project as Go language versions are forward compatible.
This PR updates the Makefile to support Go version 1.19 and above. It introduces a new variable GO_MIN_SUPPORTED_VERSION which is set to 1.19. The Makefile now includes a version check that allows compatibility with any Go version greater than or equal t
> feat: optimize go version auto set

- .github/workflows/e2e-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/openimci.yml
- config/kafka.yml
- config/minio.yml
- config/mongodb.yml
- config/notification.yml
- config/openim-msggateway.yml
- config/openim-msgtransfer.yml
- config/openim-push.yml
- config/openim-rpc-auth.yml
- config/openim-rpc-conversation.yml
- config/openim-rpc-friend.yml
- config/openim-rpc-group.yml
- config/openim-rpc-msg.yml
- config/openim-rpc-third.yml
- go.mod
- go.sum
- internal/push/offlinepush/offlinepusher.go
- internal/push/push_handler.go
- start-config.yml
> update go.mod go.sum

- go.mod
This error may be encountered on centos 7
issue  #2229
It has now been fixed, changing the three-digit version number to two-digit
> fix bug:invalid go version '1.21.2' : must match format 1.23

- pkg/common/db/mgo/msg.go
> fix: search for messag

- internal/rpc/auth/auth.go
> feat: implement to invalid token when forceKickOff user.

- internal/api/msg.go
- pkg/apistruct/manage.go
Fixes #2368
fix: message can store Ex
> fix: message can store Ex

- config/webhooks.yml
- internal/rpc/msg/callback.go
- pkg/common/config/config.go
I noticed that the afterSendSingleMsg webhook can trigger a callback after a message is sent. This appears to be global, meaning every message will callback to the business server. This is quite resource-intensive for scenarios where only messages from certain users need to be monitored. I have added a configuration option to set the users whose message callbacks need to be monitored in the configuration file. The judgment is completed on the OpenIM side, and only the corresponding users will trigger the hook. This approach can be applied to all webhooks; I have currently only implemented the handling for afterSendSingleMsg.
For example, in a customer service bot scenario, the existing webhook cannot monitor only the messages sent to the customer service account. To achieve this …
> feat: add webhook AttentionIds

- internal/rpc/group/notification.go
Fixes #2366
Group admin application can synchronize.
> fix: group application

- config/openim-rpc-third.yml
- go.mod
- internal/rpc/third/third.go
- pkg/common/config/config.go
As I mentioned in [#1923 ], the support library for Qiniu Kodo has not been merged properly. I noticed that the project structure has changed and the code related to S3 has been moved to the Tools project. I have completed these changes and also submitted [PR](https://github.com/openimsdk/tools/pull/91) in the tools project.
Fixes #
#1923
> feature: support for Kodo

- internal/rpc/group/notification.go
Fixes #2445
fix: display is read
> fix: display is read

- internal/rpc/group/group.go
The current code callback object is the current operating user; it should callback the member information being operated on.
Fixes #2410
> fix: #2410 BeforeMemberJoinGroup callback member error

- internal/api/msg.go
- internal/msgtransfer/init.go
- internal/msgtransfer/online_history_msg_handler.go
- internal/msgtransfer/online_msg_to_mongo_handler.go
- internal/push/onlinepusher.go
- internal/push/push_handler.go
- pkg/common/storage/controller/msg.go
- pkg/common/storage/database/mgo/msg.go
- pkg/common/storage/model/msg.go
1. Unify the receiver of structure methods and use pointer
2. Use errors.Is to make error judgments
3. Fix word spelling errors
> fix Details

- config/redis.yml
- go.mod
- go.sum
- internal/msgtransfer/online_history_msg_handler.go
- internal/push/offlinepush/dummy/push.go
- internal/push/push_handler.go
- pkg/common/cmd/root.go
- pkg/common/config/config.go
- pkg/common/prommetrics/grpc_push.go
- pkg/common/prommetrics/rpc.go
- pkg/common/storage/cache/redis/batch_handler.go
- pkg/rpccache/conversation.go
Fixes #2583
Add long time push msg in prometheus.
> feat: add long time push msg in prometheus

- docker-compose.yml
$ docker-compose --version
Docker Compose version v2.29.1-desktop.1
WARN[0000] open-im-server/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
> fix: the attribute version is obsolete, remove it

- config/webhooks.yml
- internal/rpc/relation/callback.go
- internal/rpc/relation/friend.go
- pkg/callbackstruct/constant.go
- pkg/callbackstruct/friend.go
- pkg/common/config/config.go
Fixes #2679
feat: add friend agree after callback
> feat: add friend agree after callback

- config/webhooks.yml
- docker-compose.yml
- go.mod
- go.sum
- internal/rpc/msg/callback.go
- internal/rpc/msg/filter.go
- pkg/common/config/config.go
> feat: Msg filter

- internal/rpc/group/group.go
Fixes #2776
fix: Change group member roleLevel can`t send notification
> fix: Change group member roleLevel can`t send notification

- internal/msgtransfer/init.go
- internal/msgtransfer/online_history_msg_handler.go
- pkg/common/storage/controller/msg_transfer.go
> fix: set own read seq in MongoDB when sender send a message.

- .github/workflows/cleanup-after-milestone-prs-merged.yml
- config/notification.yml
- internal/rpc/group/group.go
> fix: solve err Notification when setGroupInfo.

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [OpenIM Guru](https://gurubase.io/g/openim) to Gurubase. OpenIM Guru uses the data from this repo and data from the [docs](https://docs.openim.io/) to answer questions by leveraging the LLM.
In this PR, I showcased the "OpenIM Guru", which highlights that OpenIM now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
> Introducing OpenIM Guru on Gurubase.io

- pkg/common/storage/database/mgo/group.go
Fixes #2841
fix: get group return repeated result
> fix: get group return repeated result

- config/openim-push.yml
- internal/push/offlinepush/jpush/body/notification.go
- internal/push/offlinepush/jpush/push.go
- internal/push/offlinepush_handler.go
- internal/push/push_handler.go
Fixed #2540
Fixed #2706
I have read the CLA Document and I hereby sign the CLA
> fix(push): push content with jpush

- internal/rpc/auth/auth.go
- pkg/common/storage/controller/auth.go
- pkg/common/storage/controller/msg.go
> fix: Remove admin token in redis

- internal/push/push_handler.go
The 5th argument of webhookBeforeOfflinePush should not be nil, this PR will fix that problem.
> Fix Push2User webhookBeforeOfflinePush

- internal/rpc/auth/auth.go
- internal/rpc/msg/as_read.go
- pkg/common/storage/controller/msg.go
> fix: Wrong Redis Error Check

- .env
- config/openim-api.yml
- config/openim-msggateway.yml
- config/openim-msgtransfer.yml
- config/openim-push.yml
- config/openim-rpc-auth.yml
- config/openim-rpc-conversation.yml
- config/openim-rpc-friend.yml
- config/openim-rpc-group.yml
- config/openim-rpc-msg.yml
- config/openim-rpc-third.yml
- config/openim-rpc-user.yml
- config/prometheus.yml
- config/share.yml
- docker-compose.yml
> feat: Add node_exporter in docker-compose

- internal/rpc/group/notification.go
> fix: when unable EnableHistoryForNewMembers, new group member can read last one message.

- pkg/common/storage/cache/redis/token.go
- pkg/common/storage/cache/token.go
- pkg/common/storage/controller/auth.go
> fix: redis save error when KickTokens

- internal/msggateway/ws_server.go
> fix: PCAndOther multi login policy can`t get old clients correctly
